### PR TITLE
meta: Formatting for use as an external doc

### PR DESCRIPTION
**Pull request by garethtdavies**
A few required changes to use absolute links in order to pull into the docs and a few cleanups.

Change-type: patch
Signed-off-by: Gareth Davies gareth@balena.io

### CODE REVIEW

**Comment by garethtdavies** [comment]
Note there is a followup PR here that will then pull in this README to the main docs https://github.com/balena-io/docs/pull/1313

**Comment by garethtdavies** [comment]
@balena-ci retest

**Review by tmigone — APPROVED** [review]
lgtm!

**Comment by tmigone** [comment]
@balena-ci retest

**Comment by nazrhom** [comment]
@balena-ci retest

**Pull request merged**
